from pathlib import Path
p=Path('duty_match.html')
s=p.read_text()
old='''    @media(max-width:760px){\n      .page-wrap{padding:10px 7px}\n      .hero-band{margin-bottom:7px;padding:8px 10px}\n      .hero-sub{font-size:.67rem}\n      .notice-bar,.linked-context-panel{margin-bottom:7px;padding:7px 9px}\n      .sum-bar{gap:4px;margin-bottom:7px}\n      .sum-chip{padding:4px 6px}\n      .sum-n{font-size:.92rem}.sum-l{font-size:.58rem}\n      .mc{margin-bottom:7px;border-radius:10px}\n      .mc-head{padding:7px 9px;gap:6px}\n      .mc-name{font-size:.78rem}.mc-sub{font-size:.6rem}\n      .mc-body{padding:5px 6px 7px}\n      .dt-wrap{overflow:visible;margin-bottom:4px}\n      .dt{min-width:0;table-layout:fixed;font-size:.72rem}\n      .dt thead{display:none}\n      .duty-row-inner{min-height:34px;padding:3px 5px;gap:4px}\n      .d-icon{width:18px;font-size:.8rem}\n      .d-label{font-size:.7rem;line-height:1.12}\n      .d-memo,.d-time{display:none}\n      .persons-wrap{flex:0 0 78px;justify-content:flex-end}\n      .person-quick-edit{width:78px;max-width:78px;padding:4px 5px;font-size:.66rem}\n      .st{font-size:.56rem;padding:1px 4px}\n      .add-duty-row{padding:4px 6px;font-size:.68rem}\n      .mc-body-actions{gap:5px!important;padding-top:3px!important}\n      .mc-body-actions .btn,.mc-body-actions .btn-line-copy{padding:6px 8px!important;font-size:.65rem!important;min-height:34px!important}\n    }'''
new='''    @media(max-width:760px){\n      .page-wrap{padding:10px 7px}\n      .hero-band{margin-bottom:8px;padding:10px 11px}\n      .hero-title{font-size:1.05rem;line-height:1.35}\n      .hero-sub{font-size:.8rem;line-height:1.55}\n      .notice-bar,.linked-context-panel{margin-bottom:8px;padding:10px 11px;font-size:.86rem;line-height:1.55}\n      .template-help{font-size:.86rem;line-height:1.6;padding:11px 12px}\n      .sum-bar{gap:5px;margin-bottom:8px}\n      .sum-chip{padding:6px 7px}\n      .sum-n{font-size:1.05rem}.sum-l{font-size:.68rem}\n      .mc{margin-bottom:8px;border-radius:10px}\n      .mc-head{padding:10px 10px;gap:7px}\n      .mc-name{font-size:1rem;line-height:1.35}.mc-sub{font-size:.76rem;line-height:1.45}\n      .mc-prog{font-size:.95rem}\n      .mc-arrow{font-size:1rem}\n      .mc-edit-btn{font-size:.78rem;padding:5px 8px}\n      .mc-body{padding:7px 7px 9px}\n      .dt-wrap{overflow:visible;margin-bottom:5px}\n      .dt{min-width:0;table-layout:fixed;font-size:.84rem}\n      .dt thead{display:none}\n      .duty-row-inner{min-height:46px;padding:6px 6px;gap:6px}\n      .d-icon{width:22px;font-size:1rem}\n      .d-label{font-size:.88rem;line-height:1.3;min-width:0;overflow-wrap:anywhere}\n      .d-memo,.d-time{display:none}\n      .persons-wrap{flex:0 0 92px;justify-content:flex-end}\n      .person-quick-edit{width:92px;max-width:92px;padding:6px 6px;font-size:.78rem}\n      .st{font-size:.68rem;padding:3px 6px}\n      .add-duty-row{min-height:42px;padding:7px 7px;font-size:.84rem}\n      .mc-body-actions{gap:6px!important;padding-top:5px!important}\n      .mc-body-actions .btn,.mc-body-actions .btn-line-copy{padding:8px 10px!important;font-size:.78rem!important;min-height:42px!important}\n    }'''
if old not in s:
    raise SystemExit('target mobile css block not found')
s=s.replace(old,new,1)
p.write_text(s)
print('duty_match mobile typography enlarged')
